### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [amitkb3/prj-rev-bwfs-tea-cozy#5]
Needs Improvement.

Unfortunately this site needs some fixing. I made some suggestions that will help get you on the right track.  Everything is off center plus there is a lot of css issues.  After you make some of the adjustments try to get everything completely center together.

I also leaving you a link to the complete solution so you can have a reference point.

https://gist.github.com/eharris99/2a1dc067c77b023576432649a9480a72

If you feel lost please reach out to the advisors so they can answer any questions you may have.  Sometimes flexbox is tricky and we need some help understanding how to position everything.

**Comment by amitkb3** [comment]
thanks for your feedback. Will incorporate the changes.
